services:
  - type: web
    name: alset-streaming-hub
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: STREAM_UPSTREAM
        value: https://alset-streaming-hub.lhmolam-877.workers.dev
      - key: NODE_VERSION
        value: "20"
